App\Entity\CooperativeGroup:
  attributes:
    id:
      groups: [
        "cooperativegroup:collection:get",
        "cooperativegroup:item:get"
      ]
    mob_data_id:
      groups: [
        'cooperativegroup:collection:get',
        'cooperativegroup:collection:post',
        'cooperativegroup:item:get',
        'cooperativegroup:item:put',
        'cooperativegroup:item:patch'
      ]
    cooperative_group_name:
      groups: [
        'cooperativegroup:collection:get',
        'cooperativegroup:collection:post',
        'cooperativegroup:item:get',
        'cooperativegroup:item:put',
        'cooperativegroup:item:patch'
      ]
    type:
      groups: [
        'cooperativegroup:collection:get',
        'cooperativegroup:collection:post',
        'cooperativegroup:item:get',
        'cooperativegroup:item:put',
        'cooperativegroup:item:patch'
      ]
    cooperative_group_type:
      groups: [
        'cooperativegroup:collection:get',
        'cooperativegroup:collection:post',
        'cooperativegroup:item:get',
        'cooperativegroup:item:put',
        'cooperativegroup:item:patch'
      ]
    cooperative_group_function:
      groups: [
        'cooperativegroup:collection:get',
        'cooperativegroup:collection:post',
        'cooperativegroup:item:get',
        'cooperativegroup:item:put',
        'cooperativegroup:item:patch'
      ]
    offers_livestock_marketing:
      groups: [
        'cooperativegroup:collection:get',
        'cooperativegroup:collection:post',
        'cooperativegroup:item:get',
        'cooperativegroup:item:put',
        'cooperativegroup:item:patch'
      ]
    offers_livestock_products:
      groups: [
        'cooperativegroup:collection:get',
        'cooperativegroup:collection:post',
        'cooperativegroup:item:get',
        'cooperativegroup:item:put',
        'cooperativegroup:item:patch'
      ]
    number_male_members:
      groups: [
        'cooperativegroup:collection:get',
        'cooperativegroup:collection:post',
        'cooperativegroup:item:get',
        'cooperativegroup:item:put',
        'cooperativegroup:item:patch'
      ]
    number_female_members:
      groups: [
        'cooperativegroup:collection:get',
        'cooperativegroup:collection:post',
        'cooperativegroup:item:get',
        'cooperativegroup:item:put',
        'cooperativegroup:item:patch'
      ]
    user_id:
      groups: [
        'cooperativegroup:collection:get',
        'cooperativegroup:collection:post',
        'cooperativegroup:item:get',
        'cooperativegroup:item:put',
        'cooperativegroup:item:patch'
      ]
    isCooperative:
      groups: [
        "cooperativegroup:collection:get",
        "cooperativegroup:item:get"
      ]
    isGroup:
      groups: [
        "cooperativegroup:collection:get",
        "cooperativegroup:item:get"
      ]
    datetime:
      groups: [
        'cooperativegroup:collection:get',
        'cooperativegroup:collection:post',
        'cooperativegroup:item:get',
        'cooperativegroup:item:put',
        'cooperativegroup:item:patch'
      ]
    ip_address:
      groups: [
        'cooperativegroup:collection:get',
        'cooperativegroup:collection:post',
        'cooperativegroup:item:get',
        'cooperativegroup:item:put',
        'cooperativegroup:item:patch'
      ]
    status:
      groups: [
        'cooperativegroup:collection:get',
        'cooperativegroup:collection:post',
        'cooperativegroup:item:get',
        'cooperativegroup:item:put',
        'cooperativegroup:item:patch'
      ]
    ipAddress:
      groups: [
        "cooperativegroup:collection:get",
        "cooperativegroup:item:get"
      ]
    createdAt:
      groups: [
        "cooperativegroup:collection:get",
        "cooperativegroup:item:get"
      ]
    createdBy:
      groups: [
        "cooperativegroup:collection:get",
        "cooperativegroup:item:get"
      ]
    updatedAt:
      groups: [
        "cooperativegroup:collection:get",
        "cooperativegroup:item:get"
      ]
    updatedBy:
      groups: [
        "cooperativegroup:collection:get",
        "cooperativegroup:item:get"
      ]
    regionId:
      groups: [
        "cooperativegroup:collection:get",
        "cooperativegroup:item:get"
      ]
    districtId:
      groups: [
        "cooperativegroup:collection:get",
        "cooperativegroup:item:get"
      ]
    wardId:
      groups: [
        "cooperativegroup:collection:get",
        "cooperativegroup:item:get"
      ]
    villageId:
      groups: [
        "cooperativegroup:collection:get",
        "cooperativegroup:item:get"
      ]
