App\Entity\CoreCooperativeGroup:
  attributes:
    id:
      groups: [
        "corecooperativegroup:collection:get",
        "corecooperativegroup:item:get"
      ]
    mobDataId:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    cooperativeGroupName:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    type:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    cooperativeGroupType:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    cooperativeGroupFunction:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    offersLivestockMarketing:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    offersLivestockProducts:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    numberMaleMembers:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    numberFemaleMembers:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    userId:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    isCooperative:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    isGroup:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    datetime:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    ipAddress:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    status:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    createdAt:
      groups: [
        "corecooperativegroup:collection:get",
        "corecooperativegroup:item:get"
      ]
    createdBy:
      groups: [
        "corecooperativegroup:collection:get",
        "corecooperativegroup:item:get"
      ]
    updatedAt:
      groups: [
        "corecooperativegroup:collection:get",
        "corecooperativegroup:item:get"
      ]
    updatedBy:
      groups: [
        "corecooperativegroup:collection:get",
        "corecooperativegroup:item:get"
      ]
    countryId:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    regionId:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    districtId:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    wardId:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]
    villageId:
      groups: [
        'corecooperativegroup:collection:get',
        'corecooperativegroup:collection:post',
        'corecooperativegroup:item:get',
        'corecooperativegroup:item:put',
        'corecooperativegroup:item:patch'
      ]

