App\Entity\Herd:
    attributes:
        id:
            groups: [
                "herd:collection:get",
                "herd:item:get"
            ]
        name:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        countryId:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        speciesId:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        regionId:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        districtId:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        wardId:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        villageId:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        orgId:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        clientId:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        mobDataId:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        mobFarmId:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        latitude:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        longitude:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        mapAddress:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        regDate:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        project:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        migrationId:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        farm:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        additionalAttributes:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        mobAdditionalAttributes:
            groups: [
                "herd:collection:post",
                "herd:item:put",
                "herd:item:patch"
            ]
        createdAt:
            groups: [
                "herd:collection:get",
                "herd:item:get"
            ]
        createdBy:
            groups: [
                "herd:collection:get",
                "herd:item:get"
            ]
        updatedAt:
            groups: [
                "herd:collection:get",
                "herd:item:get"
            ]
        updatedBy:
            groups: [
                "herd:collection:get",
                "herd:item:get"
            ]