App\Entity\MobImages:
    attributes:
        id:
            groups: [
                "mobimages:collection:get",
                "mobimages:item:get"
            ]
        mobDataId:
            groups: [
                "mobimages:collection:get",
                "mobimages:collection:post",
                "mobimages:item:get",
                "mobimages:item:put",
                "mobimages:item:patch"
            ]
        coreTableId:
            groups: [
                "mobimages:collection:get",
                "mobimages:collection:post",
                "mobimages:item:get",
                "mobimages:item:put",
                "mobimages:item:patch"
            ]
        coreTableType:
            groups: [
                "mobimages:collection:get",
                "mobimages:collection:post",
                "mobimages:item:get",
                "mobimages:item:put",
                "mobimages:item:patch",
            ]
        imageFilePath:
            groups: [
                "mobimages:collection:get",
                "mobimages:collection:post",
                "mobimages:item:get",
                "mobimages:item:put",
                "mobimages:item:patch"
            ]
        imageServerLocation:
            groups: [
                "mobimages:collection:get",
                "mobimages:collection:post",
                "mobimages:item:get",
                "mobimages:item:put",
                "mobimages:item:patch"
            ]
        createdAt:
            groups: [
                "mobimages:collection:get",
                "mobimages:collection:post",
                "mobimages:item:get",
                "mobimages:item:put",
                "mobimages:item:patch"
            ]
        createdBy:
            groups: [
                "mobimages:collection:get",
                "mobimages:collection:post",
                "mobimages:item:get",
                "mobimages:item:put",
                "mobimages:item:patch"
            ]
