#index:
#    path: /
#    controller: App\Controller\DefaultController::index

authentication_token:
  path: /authentication_token
  methods: ['POST']

app_sync:
  path: /sync
  controller: App\Controller\SyncController::sync
  methods: ['POST']
app_syncimage:
  path: /upload_file_new
  controller: App\Controller\SyncController::upload_file_new
  methods: ['POST']