App\Entity\Animal:
  collectionOperations:
    get:
      method: get
      path: /animals
      filters: ['animal.search_filter', 'country_isocode_filter', 'property_filter']
      normalization_context:
        groups: ['animal:collection:get']
      openapi_context:
        parameters:
          - name: tagId
            in: query
            description: 'The animal''s tag ID<br><br>*Example value: T19000001*'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: string
            style: form
            explode: false
            allowReserved: false
          - name: 'tagId[]'
            in: query
            description: 'Select multiple tag IDs'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: array
              items:
                type: string
            style: form
            explode: true
            allowReserved: false
          - name: animalType
            in: query
            description: 'The type of a given animal<br><br>*Example value: 1*'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: integer
            style: form
            explode: false
            allowReserved: false
          - name: 'animalType[]'
            in: query
            description: 'Select multiple animal types'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: array
              items:
                type: integer
            style: form
            explode: true
            allowReserved: false
          - name: page
            in: query
            description: 'The collection page number'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: integer
              default: 1
            style: form
            explode: false
            allowReserved: false
          - name: pagination
            in: query
            description: 'Enable or disable pagination'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: boolean
            style: form
            explode: false
            allowReserved: false
          - name: countryCode
            in: query
            description: 'Provide the country ISO 3166-1 alpha-2 code'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: string
            style: form
            explode: false
            allowReserved: false
    post:
      method: post
      path: /animals
      denormalization_context:
        groups: [ 'animal:collection:post' ]
      openapi_context:
        description:
          '<h3>Creates a Animal resource</h3><p>The following properties are **required** and need to be provided in the request body:
          </p>`countryId`<p>`tagId`</p><p>All other properties are **optional**.</p>'
  itemOperations:
    get:
      method: get
      path: /animals/{id}
      normalization_context:
        groups: [ 'animal:item:get' ]
    put:
      method: put
      path: /animals/{id}
      denormalization_context:
        groups: [ 'animal:item:put' ]
      openapi_context:
        description:
          '<h3>Replaces the Animal resource specified by the `id` parameter</h3><p>The following properties are **required** and need to be provided in the request body:
          </p>`countryId`<p>`tagId`</p><p>All other properties are **optional**.</p>'
    patch:
      method: patch
      path: /animals/{id}
      denormalization_context:
        groups: [ 'animal:item:patch' ]
      openapi_context:
        description:
          '<h3>Updates the Animal resource specified by the `id` parameter</h3><p>The following properties are **required** and need to be provided in the request body:
          </p>`countryId`<p>`tagId`</p><p>All other properties are **optional**.</p>'
