App\Entity\CountryUnits:
  collectionOperations:
    get:
      method: get
      path: /level
      filters: [ 'countryunits.search_filter','country_isocode_filter', 'property_filter' ]
      normalization_context:
        groups: [ 'countryunits:collection:get' ]
      openapi_context:
        parameters:
          - name: countryCode
            in: query
            description: 'Provide the country ISO 3166-1 alpha-2 code'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: string
            style: form
            explode: false
            allowReserved: false
          - name: level
            in: query
            description: 'Select the level of adminstration'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: string
            style: form
            explode: false
            allowReserved: false
  itemOperations:
    get:
      method: get
      path: /level/{id}
      normalization_context:
        groups: [ 'countryunits:item:get' ]