App\Entity\Herd:
  collectionOperations:
    get:
      method: get
      path: /herds
      filters: [ 'country_isocode_filter', 'property_filter' ]
      normalization_context:
        groups: [ 'herd:collection:get' ]
      openapi_context:
        parameters:
          - name: mobDataId
            in: query
            description: 'Filter by the mobile specific data ID'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: string
            style: form
            explode: false
            allowReserved: false
          - name: 'mobDataId[]'
            in: query
            description: 'Select multiple data IDs'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: array
              items:
                type: string
            style: form
            explode: true
            allowReserved: false
          - name: mobFarmId
            in: query
            description: 'Filter by the mobile specific farm ID'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: string
            style: form
            explode: false
            allowReserved: false
          - name: 'mobFarmId[]'
            in: query
            description: 'Select multiple farm IDs'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: array
              items:
                type: string
            style: form
            explode: true
            allowReserved: false

    post:
      method: post
      path: /herds
      denormalization_context:
        groups: [ 'herd:collection:post' ]
      openapi_context:
        description:
          '<h3>Creates a Herd resource</h3><p>The following properties are **required** and need to be provided in the request body:
          </p>`countryId`<p>All other properties are **optional**.</p>'
  itemOperations:
    get:
      method: get
      path: /herds/{id}
      normalization_context:
        groups: [ 'herd:item:get' ]
    put:
      method: put
      path: /herds/{id}
      denormalization_context:
        groups: [ 'herd:item:put' ]
      openapi_context:
        description:
          '<h3>Replaces the Herd resource specified by the `id` parameter</h3><p>The following properties are **required** and need to be provided in the request body:
          </p>`isActive`<p>`isDeleted`</p><p>`name`</p><p>All other properties are **optional**.</p>'
    patch:
      method: patch
      path: /herds/{id}
      denormalization_context:
        groups: [ 'herd:item:patch' ]
      openapi_context:
        description:
          '<h3>Updates the Herd resource specified by the `id` parameter</h3><p>The following properties are **required** and need to be provided in the request body:
          </p>`name`<p>All other properties are **optional**.</p>'
