App\Entity\MasterList:
  collectionOperations:
    get:
      method: get
      path: /master_lists
      filters: [ 'masterlist.search_filter', 'property_filter' ]
      normalization_context:
        groups: [ 'masterlist:collection:get' ]
      openapi_context:
        parameters:
          - name: listType
            in: query
            description:  'The path to a given master list type <br><br> *For example: 1*'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: string
            style: form
            explode: false
            allowReserved: false
          - name: isActive
            in: query
            description: 'filter by is active'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: integer
            style: form
            explode: false
            allowReserved: false
  itemOperations:
    get:
      method: get
      path: /master_lists/{id}
      normalization_context:
        groups: [ 'masterlist:item:get' ]