App\Entity\MasterList:
  collectionOperations:
    get:
      method: get
      path: /master_list
      normalization_context:
        groups: [ 'MasterList:collection:get' ]

  itemOperations:
    get:
      method: get
      path: /master_list/{list_type_id}
      normalization_context:
        groups: [ 'MasterList:item:get' ]

