App\Entity\MasterList:
  collectionOperations:
    get:
      method: get
      path: /master_list
      filters: [ 'country_isocode_filter', 'property_filter' ]
      normalization_context:
        groups: [ 'MasterList:collection:get' ]

  itemOperations:
    get:
      method: get
      path: /master_list/{id}
      normalization_context:
        groups: [ 'MasterList:item:get' ]

