App\Entity\MasterList:
  collectionOperations:
    get:
      method: get
      path: /master_lists
      filters: [ 'masterlist.search_filter', 'list_type_filter', 'property_filter' ]
      normalization_context:
        groups: [ 'masterlist:collection:get' ]
      openapi_context:
        parameters:
          - name: listTypeid
            in: query
            description: 'Enter the list type id acquired from master list type'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: integer
            style: form
            explode: false
            allowReserved: false
  itemOperations:
    get:
      method: get
      path: /master_lists/{id}
      normalization_context:
        groups: [ 'masterlist:item:get' ]