App\Entity\MasterList:
  collectionOperations:
    get:
      method: get
      path: /master_lists
      normalization_context:
        groups: [ 'masterlist:collection:get' ]

  itemOperations:
    get:
      method: get
      path: /master_lists/{list_type_id}
      normalization_context:
        groups: [ 'masterlist:item:get' ]