App\Entity\ParameterLimits:
  collectionOperations:
    get:
      method: get
      path: /limits
      filters: [ 'parameterlimits.search_filter', 'country_isocode_filter', 'property_filter' ]
      normalization_context:
        groups: [ 'parameterlimits:collection:get' ]
      openapi_context:
        parameters:
          - name: id
            in: query
            description: 'The parameter limits ID<br><br>*For example: 1*'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: integer
            style: form
            explode: false
            allowReserved: false
          - name: category
            in: query
            description: 'Filter by category'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: string
            style: form
            explode: false
            allowReserved: false
          - name: message
            in: query
            description: 'Filter by Message'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: string
            style: form
            explode: false
            allowReserved: false
          - name: name
            in: query
            description: 'Filter by name'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: string
            style: form
            explode: false
            allowReserved: false
          - name: isActive
            in: query
            description: 'The parameter limits ID<br><br>*For example: 1*'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: integer
            style: form
            explode: false
            allowReserved: false
          - name: page
            in: query
            description: 'The collection page number'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: integer
              default: 1
            style: form
            explode: false
            allowReserved: false
          - name: pagination
            in: query
            description: 'Enable or disable pagination'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: boolean
            style: form
            explode: false
            allowReserved: false
          - name: fieldId
            in: query
            description: 'Filter by field Id'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: integer
            style: form
            explode: false
            allowReserved: false
          - name: speciesId
            in: query
            description: 'Filter by field Id'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: integer
            style: form
            explode: false
            allowReserved: false
#    post:
#      method: post
#      path: /parameterlimits
#      denormalization_context:
#        groups: [ 'parameterlimits:collection:post' ]
#      openapi_context:
#        description:
#          '<h3>Creates a parameterlimits resource</h3><p>The following properties are **required** and need to be provided in the request body:
#          </p>`country`<p>`farmerIsHhHead`</p>`isActive`<p>`isDeleted`</p>`name`<p>All other properties are **optional**.</p>'
  itemOperations:
    get:
      method: get
      path: /parameterlimits/{id}
      normalization_context:
        groups: [ 'parameterlimits:item:get' ]
#    put:
#      method: put
#      path: /parameterlimits/{id}
#      denormalization_context:
#        groups: [ 'parameterlimits:item:put' ]
#      openapi_context:
#        description:
#          '<h3>Replaces the Farm resource specified by the `id` parameter</h3><p>The following properties are **required** and need to be provided in the request body:
#           </p>`country`<p>`farmerIsHhHead`</p>`isActive`<p>`isDeleted`</p>`name`<p>All other properties are **optional**.</p>'
#    patch:
#      method: patch
#      path: /parameterlimits/{id}
#      denormalization_context:
#        groups: [ 'parameterlimits:item:patch' ]
#      openapi_context:
#        description:
#          '<h3>Updates the Farm resource specified by the `id` parameter</h3><p>The following properties are **required** and need to be provided in the request body:
#          </p>`farmerIsHhHead`<p>All other properties are **optional**.</p>'

