# config/api_platform/sync.yaml
App\Controller\SyncController:
  itemOperations: []
  collectionOperations:
        post_sync:
          method: 'POST'
          path: '/sync'
          controller: 'App\Controller\SyncController::sync'
          openapi_context:
            summary: 'Synchronize data'
            description: 'Synchronize data between local and remote databases.'
            responses:
              200:
                description: 'Data synchronized successfully'
              400:
                description: 'Bad Request'

