App\Entity\User:
  collectionOperations:
    get:
      method: get
      path: /user
      filters: [ 'user.search_filter', 'country_isocode_filter', 'property_filter' ]
      normalization_context:
        groups: [ 'user:collection:get' ]
      openapi_context:
        parameters:
          - name: id
            in: query
            description: 'The user ID<br><br>*For example: 1*'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: integer
            style: form
            explode: false
            allowReserved: false
          - name: 'id[]'
            in: query
            description: 'Provide multiple farm IDs'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: array
              items:
                type: integer
            style: form
            explode: true
            allowReserved: false
          - name: page
            in: query
            description: 'The collection page number'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: integer
              default: 1
            style: form
            explode: false
            allowReserved: false
          - name: pagination
            in: query
            description: 'Enable or disable pagination'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: boolean
            style: form
            explode: false
            allowReserved: false
          - name: countryCode
            in: query
            description: 'Provide the country ISO 3166-1 alpha-2 code'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: string
            style: form
            explode: false
            allowReserved: false
          - name: regionId
            in: query
            description: 'Filter by the Region ID'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: integer
            style: form
            explode: false
            allowReserved: false
          - name: districtId
            in: query
            description: 'Filter by the District ID'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: integer
            style: form
            explode: false
            allowReserved: false
          - name: wardId
            in: query
            description: 'Filter by the ward ID'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: integer
            style: form
            explode: false
            allowReserved: false
          - name: villageId
            in: query
            description: 'Filter by the Village ID'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: integer
            style: form
            explode: false
            allowReserved: false
    post:
      method: post
      path: /user
      denormalization_context:
        groups: [ 'user:collection:post' ]
#      openapi_context:
#        description:
#          '<h3>Creates a user resource</h3><p>The following properties are **required** and need to be provided in the request body:
#          </p>`country`<p>`farmerIsHhHead`</p>`isActive`<p>`isDeleted`</p>`name`<p>All other properties are **optional**.</p>'
  itemOperations:
    get:
      method: get
      path: /user/{id}
      normalization_context:
        groups: [ 'user:item:get' ]
    put:
      method: put
      path: /user/{id}
      denormalization_context:
        groups: [ 'user:item:put' ]
#      openapi_context:
#        description:
#          '<h3>Replaces the Farm resource specified by the `id` parameter</h3><p>The following properties are **required** and need to be provided in the request body:
#           </p>`country`<p>`farmerIsHhHead`</p>`isActive`<p>`isDeleted`</p>`name`<p>All other properties are **optional**.</p>'
    patch:
      method: patch
      path: /user/{id}
      denormalization_context:
        groups: [ 'user:item:patch' ]
#      openapi_context:
#        description:
#          '<h3>Updates the Farm resource specified by the `id` parameter</h3><p>The following properties are **required** and need to be provided in the request body:
#          </p>`farmerIsHhHead`<p>All other properties are **optional**.</p>'

